### ISSUE TITLE
[feat]: Add support to use  ionImgViewer directive on img element

### ISSUE THREAD

**Issue by danconte72** [SimonGolms/ngx-ionic-image-viewer#10]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

Img is easy to manipulate the style.
I've tested and the highResSrc works.
Seen that img element lose src once ionImgViewer directive is applied

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by SimonGolms** [comment]
Thanks for open a new feature request. Let's see what I can do.
For now, it should be possible via `ng-src`?

**Comment by SimonGolms** [comment]
Hi @danconte72, can please provide some more information about what exactly is meant by your feature request, like a code snippet, stackblitz, screenshot or gif?

The following should work:
```html
<img ionImgViewer src="https://example.com/image.jpg"/>
```

**Comment by JeongJun-Lee** [comment]
I need this feature, because I want to use this component in <ion-slide> tag.
