### ISSUE TITLE
[feat]: When img src is null and the image is clicked, pls do not anything or show other alternative image..

### ISSUE THREAD

**Issue by JeongJun-Lee** [SimonGolms/ngx-ionic-image-viewer#13]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

I am using the directive in the img tag like below. 
<img [src]="image" ionImgViewer onerror="src='assets/imgs/no-image.png'"/>

And the image src is null, the alternative(no-image.png) will be displayed like below.
![image](https://user-images.githubusercontent.com/11474775/72835684-ffb03180-3cac-11ea-88d7-82d5229c47ac.png)

But, when I clicked the image to enlarge it. It shows like below.
![image](https://user-images.githubusercontent.com/11474775/72835880-5a498d80-3cad-11ea-9c4a-1e9d7231fafe.png)

**Describe Preferred Solution**

When img src is null and the image is clicked, pls do not anything or show other user assigned alternative image like no-img.png.

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by SimonGolms** [comment]
Hi @JeongJun-Lee, thanks for your feature request. Let me see what I can do in the next few days to make this happen.

**Comment by JeongJun-Lee** [comment]
Hi, @SimonGolms actually maybe it's not a FR. It looks like a issue because it just needs a error handling in case img src is null. Thanks.

**Comment by SimonGolms** [comment]
I could already reproduce it and I am already working on a solution. Haven't had much time to do the final tests in the last few days.
