### ISSUE TITLE
[bug]: When zooming and drag the image to left or right the image position changed

### ISSUE THREAD

**Issue by ahmadwa** [SimonGolms/ngx-ionic-image-viewer#14]
# Bug Report

**Ionic version:**

[x] **4.11.7**

**Current behavior:**

when I move image to left or right after zooming, the image position changed on the screen.

**Expected behavior:**

when I move image to left or right after zooming, the image position must be not changed.

**Steps to reproduce:**

1- tap the image
2- the image on screen now
3- try to zoom in
4- stop zooming
5- now try to drag image to left or to right, the image position changed and not move to desired direction.

**Related code:**

```
<img width="150" height="150" src="{{ message?.message }}" ionImgViewer scheme="dark" />
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.7
   @angular-devkit/build-angular : 0.803.22
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.2, (and 14 other plugins)

Utility:

   cordova-res : 0.8.1 
   native-run  : 0.2.7 (update available: 0.3.0)

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v12.14.0 (/usr/local/bin/node)
   npm        : 6.13.4
   OS         : macOS Catalina
   Xcode      : Xcode 11.2.1 Build version 11B500
```

**Comment by SimonGolms** [comment]
Hi @ahmadwa, thanks for opening the bug. I think this is a current bug with the swiper implementation of ionic: https://github.com/ionic-team/ionic/issues/19638

**Comment by ahmadwa** [comment]
@SimonGolms thanks for your reply.
I don't use slider

`<ion-content #scrollArea [scrollEvents]="true" (ionScrollStart)="logScrollStart()" (ionScroll)="logScrolling($event)" (ionScrollEnd)="logScrollEnd()">

  <ion-grid *ngIf="messages?.length > 0">
      <ion-row *ngFor="let message of messages">

        <ion-col>
          <div class="Inline">
            <img src="{{ message.senderId === buddy.id ? buddy?.avatar : fbAuth.fbUser.avatar}}" class="circular">
          </div>
          <div class="InlineTop">
            <span style="padding:5px;">{{ message.senderId === buddy.id ? buddy?.displayName : fbAuth.fbUser.displayName }}</span>
          </div>
          <br />
          <div class="Inline">
            <span *ngIf="message.messageType === 'Text'" class="{{messageClass}} user-message">{{ message?.message }}</span>
            <span *ngIf="message.messageType === 'Image'" class="{{messageClass}} user-message">
              <img *ngIf="message.message === 'assets/icons/loading.svg'" width="50" height="50" src="{{ message?.message }}" />
              <img *ngIf="message.message !== 'assets/icons/loading.svg'" width="150" height="150" src="{{ message?.message }}" (click)="viewImage(message.message)" />
            </span>
            <div class="time {{messageClass}}">
              <br>{{ message?.fbTimestamp?.seconds * 1000 | date:'yyyy/MM/dd h:mm:ss a' }}
            </div>
          </div>
        </ion-col>

      </ion-row>
    </ion-grid>

</ion-content>`

**Comment by ahmadwa** [comment]
@SimonGolms Thanks for your reply.
I'm not using slide

my code

`<ion-content #scrollArea [scrollEvents]="true" (ionScrollStart)="logScrollStart()" (ionScroll)="logScrolling($event)" (ionScrollEnd)="logScrollEnd()">

  <ion-grid *ngIf="messages?.length > 0">
      <ion-row *ngFor="let message of messages">

        <ion-col>
          <div class="Inline">
            <img src="{{ message.senderId === buddy.id ? buddy?.avatar : fbAuth.fbUser.avatar}}" class="circular">
          </div>
          <div class="InlineTop">
            <span style="padding:5px;">{{ message.senderId === buddy.id ? buddy?.displayName : fbAuth.fbUser.displayName }}</span>
          </div>
          <br />
          <div class="Inline">
            <span *ngIf="message.messageType === 'Text'" class="{{messageClass}} user-message">{{ message?.message }}</span>
            <span *ngIf="message.messageType === 'Image'" class="{{messageClass}} user-message">
              <img *ngIf="message.message === 'assets/icons/loading.svg'" width="50" height="50" src="{{ message?.message }}" />
              <img *ngIf="message.message !== 'assets/icons/loading.svg'" width="150" height="150" src="{{ message?.message }}" ionImgViewer scheme="dark" />
            </span>
            <div class="time {{messageClass}}">
              <br>{{ message?.fbTimestamp?.seconds * 1000 | date:'yyyy/MM/dd h:mm:ss a' }}
            </div>
          </div>
        </ion-col>

      </ion-row>
    </ion-grid>

</ion-content>`

**Comment by SimonGolms** [comment]
@ahmadwa you not but `ionImgViewer` uses `<ion-slide>` to show the image and therefore relays on the swiper implementation of ionic.
Link to source code: [viewer-modal.component.html](https://github.com/SimonGolms/ngx-ionic-image-viewer/blob/fabc8e5/projects/ngx-ionic-image-viewer/src/lib/viewer-modal/viewer-modal.component.html)

I can only hope that Ionic will fix it soon.
