### ISSUE TITLE
[feat]: Programmatic Usage as Controller

### ISSUE THREAD

**Issue by abz89** [SimonGolms/ngx-ionic-image-viewer#15]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**
It must be great If you provide the other usage options such as via controller. So we could bind custom method as an event on the component

**Describe Preferred Solution**
Usage via controller like ionic action sheet, alert or toast

**Describe Alternatives**

**Related Code**

**Additional Context**

Thanks

**Comment by SimonGolms** [comment]
Good idea, if you have already developed something in this direction, any help and PR is very welcome.

**Comment by SimonGolms** [comment]
Hi @abz89,
with the latest release (#22) of version 0.7.0 you can now use the component with the `ModalController`.

```js
import { ModalController } from '@ionic/angular';
import { ViewerModalComponent } from 'ngx-ionic-image-viewer';

export class HomePage {

  constructor(public modalController: ModalController) {}

  async openViewer() {
    const modal = await this.modalController.create({
      component: ViewerModalComponent,
      componentProps: {
        src: "./assets/img/demo.jpg"
      },
      cssClass: 'ion-img-viewer'
      keyboardClose: true,
      showBackdrop: true
    });

    return await modal.present();
  }
}
```

```html
<ion-button (click)="openViewer()">Open Viewer</ion-button>
```
