### ISSUE TITLE
Double tap or pinching in and out Error

### ISSUE THREAD

**Issue by leonardn** [SimonGolms/ngx-ionic-image-viewer#2]
![image](https://user-images.githubusercontent.com/5959955/68832875-03439d00-06ed-11ea-98d6-f9db4ae79e0e.png)

ionic: ^5.0.0
angular: @angular/core": "~8.1.2"

browser version its working fine with that error. 
Actual device its not working. it overlays the app with modal, no display.

**Comment by SimonGolms** [comment]
Might be related: https://github.com/nolimits4web/swiper/issues/3312
I am currently on a trip and cannot look at the problem the next 2 weeks.

**Comment by leonardn** [comment]
> Actual device its not working. it overlays the app with modal, no display.

I checked the elements from chromium devices debug. then I found this:
![image](https://user-images.githubusercontent.com/5959955/68848926-1a45b780-070c-11ea-9031-80c23e692f00.png)


Its working as expected When I targeted the .modal-wrapper and sets opacity to 1.
