### ISSUE TITLE
innerHTML

### ISSUE THREAD

**Issue by EthanCG** [SimonGolms/ngx-ionic-image-viewer#26]
Hi,
Apparently it's not working with innerHTML embedded code.
`<div [innerHTML]="contenu"></div>`
`contenu = '<img src="demoimage.png" ionImgViewer />';`

Any chance to get it work after html render ?

Thanks

**Comment by SimonGolms** [comment]
Hi @EthanCG, no, this is not supported.
> This is wanted behavior and here is why : when you write Typescript code, you aren't writing your final application. Your code needs to be compiled first.
>
> To be compiled, your code goes through a process ran by the CLI : during this process, the compiler replaces every piece of Angular code with valid JS code. [...]
>
> https://stackoverflow.com/a/51593408
