### ISSUE TITLE
zoom issues

### ISSUE THREAD

**Issue by nicowxdvd** [SimonGolms/ngx-ionic-image-viewer#4]
How can I change the maximum zoom or how much the image scales?

i think now max scale to 3...

**Comment by SimonGolms** [comment]
Hi @nicowxdvd, with PR #6 and the release of version `0.1.0` the props `slideOptions` were added and allows you to  directly access the api of the swiper instance . In your case, the following configuration the zoom ratio will be increased to 7.
```html
<ion-img-viewer src="./demo.jpg" [slideOptions]="{ zoom: { maxRatio: 7}}"></ion-img-viewer>
```
