### ISSUE TITLE
[bug]: Images loaded remotely don't load until cached.

### ISSUE THREAD

**Issue by selected-pixel-jameson** [SimonGolms/ngx-ionic-image-viewer#41]
If I load an image via http://..... it will not load initially. Once the image has been cached or if I do something to force the image to render (i.e. double tap, zoom, etc) then it will show up. 

Not doing anything fancy.

```
async presentImage() {
    event.stopPropagation();
    const modal = await this.modalController.create({
      component: ViewerModalComponent,
      componentProps: {
        srcHighRes: this.item.imageUrl,
        title: this.item.title,
      },
      cssClass: "ion-img-viewer",
      keyboardClose: true,
      showBackdrop: true,
    });

    return await modal.present();
}
```

```
<div class="img-wrapper issue-cover" (click)="presentImage()">
     <ion-img [src]="item.thumbnail"></ion-img>
</div>
```

If I were to set the srcHighRes property to item.thumbnail the image would show up when I initially click on it because it's been loaded already. But when it's set to item.imageUrl it will not load until it is cached.

**Comment by SimonGolms** [comment]
Hi @selected-pixel-jameson, in your case you create a new modal without any reference to your `<ion-img />` child. The `src` attribute is always [required](https://github.com/SimonGolms/ngx-ionic-image-viewer#src). Try this:
```js
componentProps: {
  src: this.item.imageUrl,
}
```
You know you can also use the `directive` of the `ngx-ionic-image-viewer` which solve your case directly?
```html
<ion-img ionImgViewer [title]="item.title" [src]="item.thumbnail" [srcHighRes]="item.imageUrl"></ion-img>
```

**Comment by selected-pixel-jameson** [comment]
Hi @SimonGolms Adding src to the componentProps doesn't help.  I can't use the directive on <ion-img> because this is wrapped inside another element that is clickable and I need to cancel the event propagation via `event.stopPropogation()`

```
async presentImage() {
    event.stopPropagation();
    const modal = await this.modalController.create({
      component: ViewerModalComponent,
      componentProps: {
        src: this.item.imageUrl,
      },
      cssClass: "ion-img-viewer",
      keyboardClose: true,
      showBackdrop: true,
    });

    return await modal.present();
  }
```

Still the same issue. I just see a black screen. if I click anywhere on the screen the image will then show up. But it will not show up when loading.

**Comment by selected-pixel-jameson** [comment]
As I stated, this works fine when I reference the same image URL that is being loaded in the list view of items. If I change that list to load the imageUrl instead of the the thumbnail url then the imageUrl will load fine as well, but this is not optimal as the image referenced in the imageUrl is much larger.

**Comment by selected-pixel-jameson** [comment]
Also, if I set this up to load a completely different image, but that image is referenced locally from the assets folder it works fine.  It's only an issue when loading a remote image that hasn't been cached yet.

**Comment by selected-pixel-jameson** [comment]
Oh great... so this only appears to be happening on Android devices and when using the pixel 2 device in chrome dev.

**Comment by selected-pixel-jameson** [comment]
Looks like it is a bug with Android or Ionic... I had to add this to get it to work. 

```
 img{
    min-height: 1px !important;
  }
```

**Comment by SimonGolms** [comment]
Thanks for your message and the recent workaround for Android @selected-pixel-jameson.
