### ISSUE TITLE
[feat]: Support for Ionic 5 (peer dep missing)

### ISSUE THREAD

**Issue by nelson6e65** [SimonGolms/ngx-ionic-image-viewer#46]
# Feature Request

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Describe the Feature Request**

Add compatibility with Ionic 5. 

Seems to work fine on Ionic 5. I have not found any issues, but `npm ERR! peer dep missing: @ionic/angular@4.0.0`

**Describe Preferred Solution**

Remove the peer dep missing error on install/update with npm when using Ionic 5.

**Comment by SimonGolms** [comment]
Should be fixed with PR #48
