### ISSUE TITLE
Modal Close Causes Local app modal close and freezing

### ISSUE THREAD

**Issue by elkhalifte** [SimonGolms/ngx-ionic-image-viewer#50]
i have an ionic modal page which contains some pictures if i clicked one of them to view it inside a model and closed this modal viewer my ionic modal is freezing untill u close it.

**Comment by SimonGolms** [comment]
Hi @elkhalifte, please use the `[Bug Report`](https://github.com/SimonGolms/ngx-ionic-image-viewer/issues/new?assignees=&labels=&template=bug_report.md&title=%5Bbug%5D%3A+) template and provide an reproducible example - Thanks.
