### ISSUE TITLE
Swipe error

### ISSUE THREAD

**Issue by nicowxdvd** [SimonGolms/ngx-ionic-image-viewer#7]
Hey men,
  every time I swipe the following error appears
![Captura de Pantalla 2019-12-17 a la(s) 10 32 07](https://user-images.githubusercontent.com/4203771/70999635-896e4d00-20b8-11ea-82c4-cedfbb17d971.png)

Another query, is there a possibility that this plugin works in ionc 3?

**Comment by SimonGolms** [comment]
Which version of ngx-ionic-image-viewer and ionic do you use and can you provide an appropriate code snippet or example where I can reproduce this issue? There has been a similar issue before (see #2), but this should have been fixed in version 0.0.2 (see PR #1)?

**Comment by SimonGolms** [comment]
> Another query, is there a possibility that this plugin works in ionc 3?

No and is also not planned. There exists other packages for ionic >= 3.x.

**Comment by SimonGolms** [comment]
Hi @nicowxdvd, I was able to reproduce it today and fix it with the following configuration and release a new version 0.2.0:
```javascript
sliderOpts = {
  passiveListeners: false,
};
```
